% this is the main script to generate Fig. 5d
clc
clear all
close all
%% define data
dir = '/Volumes/Pupil_data/';

% data list, [{animal},{day},{epoch}]
animal_info = [{'HYC2'},{2},{2};...
    {'HYC2'},{2},{3};...
    {'HYC3'},{8},{1};...
    {'HYC3'},{9},{1};...
    {'PPP4'},{8},{3};...
    {'PPP4'},{10},{5};...
    {'PPP4'},{11},{3};...
    {'PPP4'},{11},{5};...
    {'PPP4'},{18},{5};...
    {'PPP7'},{8},{3};...
    {'PPP7'},{8},{5};...
    {'PPP7'},{12},{1};...
    {'PPP7'},{12},{4};...
    {'PPP7'},{12},{6};...
    {'PPP7'},{14},{1};...
    {'PPP7'},{14},{3};...
    {'PPP7'},{14},{5};...
    {'PPP8'},{7},{1};...
    {'PPP8'},{7},{3};...
    {'PPP8'},{7},{5};...
    {'PPP8'},{8},{1};...
    {'PPP8'},{8},{3}];
%% gather results
pTransmission_all = []; %reset
for session_list = 1:length(animal_info)
    animalname = animal_info{session_list,1};
    day = animal_info{session_list,2};
    ep = animal_info{session_list,3};

    daystring = num2str(day);
    animaldir = [dir,animalname,'/day',daystring,'/'];
    prefix = ['day',daystring];

    disp([animalname,' Day-',num2str(day),' Ep-',num2str(ep)])
    pTransmission = CCGtransmission_pupilRippletile(animaldir,animalname,prefix,day,ep);

    if ~isempty(pTransmission)
        pTransmission_all = [pTransmission_all;pTransmission,session_list*ones(size(pTransmission(:,1)))];
    end

end
%% remove noisy pairs with pTransmission < 0.1
meanP  = max(pTransmission_all(:,1:3)');
validid = find(meanP > 0.1);
pTransmission_all_select = pTransmission_all(validid,1:3);