% this is the batch code for replay decoding, related to Fig. 2b
clc
clear all
close all;
%% define data
filedir = '/Volumes/Pupil_data/';
% list of all data,[{animal},{day},{epoch for decoding},{epoch for PF templates}]
animal_info = [{'PPP4'},{8},{[3]},{[2]};...
               {'PPP4'},{10},{[5]},{[4]};...
               {'PPP4'},{11},{[1]},{[2]};...
               {'PPP4'},{11},{[3]},{[2]};...
               {'PPP4'},{11},{[5]},{[4]};...
               {'PPP7'},{8},{[3]},{[2]};...
               {'PPP7'},{8},{[5]},{[4]};...
               {'PPP7'},{12},{[1]},{[3]};...
               {'PPP7'},{12},{[4]},{[3]};...
               {'PPP7'},{14},{[1]},{[2]};...
               {'PPP7'},{23},{[3]},{[2]};...
               {'PPP7'},{23},{[6]},{[2]};...
               {'PPP8'},{7},{[1]},{[2]};...
               {'PPP8'},{7},{[2]},{[2]};... 
               {'PPP8'},{7},{[3]},{[2]};...
               {'PPP8'},{7},{[4]},{[4]};...
               {'PPP8'},{7},{[5]},{[4]};...
               {'PPP8'},{8},{[1]},{[2]};...
               {'PPP8'},{8},{[2]},{[2]};... 
               {'PPP8'},{8},{[3]},{[2]};...
               {'PPP8'},{8},{[4]},{[4]};...
               {'PPP8'},{8},{[5]},{[4]}];
%% define parameters
cellcountthresh = 5; % minimal number of cells active in each SWR
savedata = 1; % save data
figopt = 1;% plot decoding result
%% set animal directory
for session_list = 1:length(animal_info)
    animalname = animal_info{session_list,1};
    day = animal_info{session_list,2};
    ep = animal_info{session_list,3};
    eprun = animal_info{session_list,4}; %behavior epoch used to calculate place-field template
    daystring = num2str(day);
    dir = [filedir,animalname,'/day',daystring,'/'];
    animalprefix = ['day',daystring];
    
    %% get place-field templates
    load(fullfile(dir,  [animalprefix,'.firingMapsAvg_linear.cellinfo.mat']));% load firing rate maps

    if strcmp(animalname,'PPP4') || (strcmp(animalname,'PPP8') && day == 8)
        spikes = importSpikes('basepath',dir,'CellType',"Pyramidal Cell");
    elseif strcmp(animalname,'PPP7')
        spikes = importSpikes('basepath',dir,'CellType',"Pyramidal Cell",'brainRegion',"dCA1");
    else
        spikes = importSpikes('basepath',dir,'CellType',"Pyramidal Cell",'brainRegion',"CA1");
    end
    
    animalname = [animalname,'-',animalprefix];
    spikes_select = spikes;

    if figopt
        figure(4)
        set(gcf,'position',[1150 500 250 180]);%linear
    end
      
    linfields = firingMaps_linear{eprun}.rateMaps;
    linfields_pos = firingMaps_linear{eprun}.params.x;    
    linfields_pos = linfields_pos - min(linfields_pos); % adjust the start to 0
    replaytrajactory = replayHSEseq_decoding_CA1_slidingwin_linfittingR2(dir,animalname,animalprefix,day,ep,spikes_select,linfields,linfields_pos,cellcountthresh,figopt,savedata);
end
